[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.bcmath", "php82Extensions.gd", "php82Extensions.tokenizer", "php82Extensions.fileinfo", "php82Extensions.curl", "php82Extensions.zip", "composer"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan storage:link && php -S 0.0.0.0:$PORT -t public"